apiVersion: v1
kind: PersistentVolume
metadata:
  name: gemeny-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/gemeny # Sur ta machine locale via Minikube
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gemeny-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
