apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - port: 3000        # Port interne du service
      targetPort: 3000  # Port du conteneur
      nodePort: 30080   # Port exposé sur localhost
