apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ton-image:latest
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: gemeny-storage
              mountPath: /app/data
      volumes:
        - name: gemeny-storage
          persistentVolumeClaim:
            claimName: gemeny-pvc
